// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Xxc8SgCf5ZyWhHUwfbVz1t5ZzoRHc1s',
    appId: '1:90123746757:web:e8d55bb555787571aa5fac',
    messagingSenderId: '90123746757',
    projectId: 'fitness-app-687e3',
    authDomain: 'fitness-app-687e3.firebaseapp.com',
    storageBucket: 'fitness-app-687e3.appspot.com',
    measurementId: 'G-3C0DCXLRW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVsqXAsz9cCzWylqK7sQCgSbTOAgScIU',
    appId: '1:90123746757:android:c27e17b429831e5eaa5fac',
    messagingSenderId: '90123746757',
    projectId: 'fitness-app-687e3',
    storageBucket: 'fitness-app-687e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRJ_ehRYnNv_CEIcaOEe2jZQljkM-swI',
    appId: '1:90123746757:ios:2cb975bc59a02f5faa5fac',
    messagingSenderId: '90123746757',
    projectId: 'fitness-app-687e3',
    storageBucket: 'fitness-app-687e3.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
